export const apiData = {
  events: [
    {
      awayScore: {
        current: 0,
        display: 0,
      },
      awayTeam: {
        country: {
          alpha2: "CN",
          name: "China",
        },
        id: 364370,
        name: "Lynn Vision",
        nameCode: "LVI",
        national: false,
        shortName: "Lynn Vision",
        slug: "lynn-vision",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 34,
      },
      bestOf: 3,
      changes: {
        changeTimestamp: 1692866645,
        changes: [
          "homeScore.display",
          "awayScore.display",
          "status.code",
          "status.description",
          "status.type",
          "homeScore.current",
          "awayScore.current",
          "time.currentPeriodStart",
        ],
      },
      coverage: 91,
      crowdsourcingDataDisplayEnabled: false,
      customId: "vMVcsxFWc",
      eventType: "best_of",
      finalResultOnly: false,
      hasGlobalHighlights: true,
      homeScore: {
        current: 0,
        display: 0,
      },
      homeTeam: {
        country: {
          alpha2: "MN",
          name: "Mongolia",
        },
        id: 366522,
        name: "TheMongolz",
        nameCode: "THE",
        national: false,
        shortName: "TheMongolz",
        slug: "themongolz",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 62,
      },
      id: 11545505,
      slug: "themongolz-lynn-vision",
      startTimestamp: 1692865800,
      status: {
        code: 1001,
        description: "First game",
        type: "inprogress",
      },
      time: {
        currentPeriodStartTimestamp: 1692866620,
      },
      tournament: {
        category: {
          flag: "csgo",
          id: 1572,
          name: "CS:GO",
          slug: "csgo",
          sport: {
            id: 72,
            name: "E-sports",
            slug: "esports",
          },
        },
        id: 89666,
        name: "IEM Playoffs",
        priority: 0,
        slug: "iem-playoffs",
        uniqueTournament: {
          category: {
            flag: "csgo",
            id: 1572,
            name: "CS:GO",
            slug: "csgo",
            sport: {
              id: 72,
              name: "E-sports",
              slug: "esports",
            },
          },
          country: {},
          crowdsourcingEnabled: false,
          displayInverseHomeAwayTeams: false,
          hasEventPlayerStatistics: false,
          hasPerformanceGraphFeature: false,
          id: 16163,
          name: "IEM",
          slug: "iem",
          userCount: 2141,
        },
      },
      winnerCode: 3,
    },
    {
      awayScore: {
        current: 0,
        display: 0,
      },
      awayTeam: {
        country: {
          alpha2: "MN",
          name: "Mongolia",
        },
        gender: "M",
        id: 479913,
        name: "ATOX",
        nameCode: "ATO",
        national: false,
        shortName: "ATOX",
        slug: "atox",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 7,
      },
      bestOf: 3,
      changes: {
        changeTimestamp: 1692867366,
        changes: [
          "homeScore.display",
          "awayScore.display",
          "status.code",
          "status.description",
          "status.type",
          "homeScore.current",
          "awayScore.current",
          "time.currentPeriodStart",
        ],
      },
      coverage: 91,
      crowdsourcingDataDisplayEnabled: false,
      customId: "nYQdsEeVd",
      eventType: "best_of",
      finalResultOnly: false,
      hasGlobalHighlights: true,
      homeScore: {
        current: 0,
        display: 0,
      },
      homeTeam: {
        country: {
          alpha2: "CN",
          name: "China",
        },
        id: 487729,
        name: "5yclone",
        nameCode: "5YC",
        national: false,
        shortName: "5yclone",
        slug: "5yclone",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 2,
      },
      id: 11545504,
      slug: "5yclone-atox",
      startTimestamp: 1692867000,
      status: {
        code: 1001,
        description: "First game",
        type: "inprogress",
      },
      time: {
        currentPeriodStartTimestamp: 1692867338,
      },
      tournament: {
        category: {
          flag: "csgo",
          id: 1572,
          name: "CS:GO",
          slug: "csgo",
          sport: {
            id: 72,
            name: "E-sports",
            slug: "esports",
          },
        },
        id: 89666,
        name: "IEM Playoffs",
        priority: 0,
        slug: "iem-playoffs",
        uniqueTournament: {
          category: {
            flag: "csgo",
            id: 1572,
            name: "CS:GO",
            slug: "csgo",
            sport: {
              id: 72,
              name: "E-sports",
              slug: "esports",
            },
          },
          country: {},
          crowdsourcingEnabled: false,
          displayInverseHomeAwayTeams: false,
          hasEventPlayerStatistics: false,
          hasPerformanceGraphFeature: false,
          id: 16163,
          name: "IEM",
          slug: "iem",
          userCount: 2141,
        },
      },
      winnerCode: 3,
    },
    {
      awayScore: {
        current: 0,
        display: 0,
      },
      awayTeam: {
        country: {},
        id: 388937,
        name: "B8",
        nameCode: "B8",
        national: false,
        shortName: "B8",
        slug: "b8",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 49,
      },
      bestOf: 3,
      changes: {
        changeTimestamp: 1692867728,
        changes: [
          "homeScore.display",
          "awayScore.display",
          "status.code",
          "status.description",
          "status.type",
          "homeScore.current",
          "awayScore.current",
          "time.currentPeriodStart",
        ],
      },
      coverage: 91,
      crowdsourcingDataDisplayEnabled: false,
      customId: "MDfdsjknd",
      eventType: "best_of",
      finalResultOnly: false,
      hasGlobalHighlights: true,
      homeScore: {
        current: 0,
        display: 0,
      },
      homeTeam: {
        country: {
          alpha2: "XK",
          name: "Kosovo",
        },
        id: 408009,
        name: "Bad News Eagles",
        nameCode: "BNE",
        national: false,
        shortName: "BNE",
        slug: "bad-news-eagles",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 1201,
      },
      id: 11566542,
      slug: "bad-news-eagles-b8",
      startTimestamp: 1692867600,
      status: {
        code: 1001,
        description: "First game",
        type: "inprogress",
      },
      time: {
        currentPeriodStartTimestamp: 1692867683,
      },
      tournament: {
        category: {
          flag: "csgo",
          id: 1572,
          name: "CS:GO",
          slug: "csgo",
          sport: {
            id: 72,
            name: "E-sports",
            slug: "esports",
          },
        },
        id: 109089,
        name: "CCT North Europe Playoffs",
        priority: 0,
        slug: "cct-north-europe-playoffs",
        uniqueTournament: {
          category: {
            flag: "csgo",
            id: 1572,
            name: "CS:GO",
            slug: "csgo",
            sport: {
              id: 72,
              name: "E-sports",
              slug: "esports",
            },
          },
          country: {},
          crowdsourcingEnabled: false,
          displayInverseHomeAwayTeams: false,
          hasEventPlayerStatistics: false,
          hasPerformanceGraphFeature: false,
          id: 19084,
          name: "CCT North Europe",
          slug: "cct-north-europe",
          userCount: 30,
        },
      },
      winnerCode: 3,
    },
    {
      awayScore: {
        current: 1,
        display: 1,
        period1: 1,
      },
      awayTeam: {
        country: {
          alpha2: "DE",
          name: "Germany",
        },
        id: 483987,
        name: "Sprout Academy",
        nameCode: "SAC",
        national: false,
        shortName: "Sprout Academy",
        slug: "sprout-academy",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 0,
      },
      bestOf: 3,
      changes: {
        changeTimestamp: 1692868322,
        changes: [
          "status.code",
          "status.description",
          "time.currentPeriodStart",
        ],
      },
      coverage: 90,
      crowdsourcingDataDisplayEnabled: false,
      customId: "YPJdsMETd",
      eventType: "best_of",
      finalResultOnly: false,
      hasGlobalHighlights: true,
      homeScore: {
        current: 0,
        display: 0,
        period1: 0,
      },
      homeTeam: {
        country: {
          alpha2: "EE",
          name: "Estonia",
        },
        id: 462048,
        name: "sYnck",
        nameCode: "SYN",
        national: false,
        shortName: "sYnck",
        slug: "synck",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 9,
      },
      id: 11559857,
      slug: "sprout-academy-synck",
      startTimestamp: 1692865800,
      status: {
        code: 1002,
        description: "Second game",
        type: "inprogress",
      },
      time: {
        currentPeriodStartTimestamp: 1692868267,
      },
      tournament: {
        category: {
          flag: "csgo",
          id: 1572,
          name: "CS:GO",
          slug: "csgo",
          sport: {
            id: 72,
            name: "E-sports",
            slug: "esports",
          },
        },
        id: 119962,
        name: "United21 Group D",
        priority: 0,
        slug: "united21-group-d",
        uniqueTournament: {
          category: {
            flag: "csgo",
            id: 1572,
            name: "CS:GO",
            slug: "csgo",
            sport: {
              id: 72,
              name: "E-sports",
              slug: "esports",
            },
          },
          country: {},
          crowdsourcingEnabled: false,
          displayInverseHomeAwayTeams: false,
          hasEventPlayerStatistics: false,
          hasPerformanceGraphFeature: false,
          id: 20941,
          name: "United21",
          slug: "united21",
          userCount: 2,
        },
      },
      winnerCode: 2,
    },
    {
      awayScore: {
        current: 1,
        display: 1,
        period1: 1,
        period2: 0,
      },
      awayTeam: {
        country: {
          alpha2: "UA",
          name: "Ukraine",
        },
        id: 364406,
        name: "Natus Vincere",
        nameCode: "NVI",
        national: false,
        shortName: "Natus Vincere",
        slug: "natus-vincere",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 226,
      },
      bestOf: 3,
      changes: {
        changeTimestamp: 1692866766,
        changes: [
          "status.code",
          "status.description",
          "time.currentPeriodStart",
        ],
      },
      coverage: 91,
      crowdsourcingDataDisplayEnabled: false,
      customId: "gNVcsYvWc",
      eventType: "best_of",
      finalResultOnly: false,
      hasGlobalHighlights: true,
      homeScore: {
        current: 1,
        display: 1,
        period1: 0,
        period2: 1,
      },
      homeTeam: {
        country: {
          alpha2: "RU",
          name: "Russia",
        },
        id: 366048,
        name: "Virtus.pro",
        nameCode: "VIR",
        national: false,
        shortName: "Virtus.pro",
        slug: "virtuspro",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 217,
      },
      id: 11565444,
      slug: "virtuspro-natus-vincere",
      startTimestamp: 1692856800,
      status: {
        code: 1003,
        description: "Third game",
        type: "inprogress",
      },
      time: {
        currentPeriodStartTimestamp: 1692866761,
      },
      tournament: {
        category: {
          flag: "dota-2",
          id: 1570,
          name: "Dota 2",
          slug: "dota2",
          sport: {
            id: 72,
            name: "E-sports",
            slug: "esports",
          },
        },
        id: 93691,
        name: "The International Playoffs",
        priority: 0,
        slug: "the-international-playoffs",
        uniqueTournament: {
          category: {
            flag: "dota-2",
            id: 1570,
            name: "Dota 2",
            slug: "dota2",
            sport: {
              id: 72,
              name: "E-sports",
              slug: "esports",
            },
          },
          country: {},
          crowdsourcingEnabled: false,
          displayInverseHomeAwayTeams: false,
          hasEventPlayerStatistics: false,
          hasPerformanceGraphFeature: false,
          id: 16273,
          name: "The International",
          slug: "the-international",
          userCount: 810,
        },
      },
      winnerCode: 3,
    },
    {
      awayScore: {
        current: 1,
        display: 1,
        period1: 1,
      },
      awayTeam: {
        country: {
          alpha2: "CN",
          name: "China",
        },
        id: 478866,
        name: "Limit",
        nameCode: "LIM",
        national: false,
        shortName: "Limit",
        slug: "limit",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 6,
      },
      bestOf: 2,
      changes: {
        changeTimestamp: 1692867422,
        changes: [
          "status.code",
          "status.description",
          "time.currentPeriodStart",
        ],
      },
      coverage: 91,
      crowdsourcingDataDisplayEnabled: false,
      customId: "vWkdsqCQd",
      eventType: "best_of",
      finalResultOnly: false,
      hasGlobalHighlights: true,
      homeScore: {
        current: 0,
        display: 0,
        period1: 0,
      },
      homeTeam: {
        country: {
          alpha2: "PH",
          name: "Philippines",
        },
        id: 402320,
        name: "UD Vessuwan",
        nameCode: "UVE",
        national: false,
        shortName: "UD Vessuwan",
        slug: "ud-vessuwan",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 14,
      },
      id: 11524461,
      slug: "limit-ud-vessuwan",
      startTimestamp: 1692864000,
      status: {
        code: 1002,
        description: "Second game",
        type: "inprogress",
      },
      time: {
        currentPeriodStartTimestamp: 1692867397,
      },
      tournament: {
        category: {
          flag: "dota-2",
          id: 1570,
          name: "Dota 2",
          slug: "dota2",
          sport: {
            id: 72,
            name: "E-sports",
            slug: "esports",
          },
        },
        id: 119518,
        name: "LingNeng Trendy Invitational Group Stage",
        priority: 0,
        slug: "lingneng-trendy-invitational-group-stage",
        uniqueTournament: {
          category: {
            flag: "dota-2",
            id: 1570,
            name: "Dota 2",
            slug: "dota2",
            sport: {
              id: 72,
              name: "E-sports",
              slug: "esports",
            },
          },
          country: {},
          crowdsourcingEnabled: false,
          displayInverseHomeAwayTeams: false,
          hasEventPlayerStatistics: false,
          hasPerformanceGraphFeature: false,
          id: 20868,
          name: "LingNeng Trendy Invitational",
          slug: "lingneng-trendy-invitational",
          userCount: 5,
        },
      },
      winnerCode: 2,
    },
    {
      awayScore: {
        current: 0,
        display: 0,
        period1: 2,
        period2: 3,
      },
      awayTeam: {
        country: {
          alpha2: "KR",
          name: "South Korea",
        },
        id: 364492,
        name: "Hanwha Life Esports",
        nameCode: "HLE",
        national: false,
        shortName: "HLE",
        slug: "hanwha-life-esports",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 182,
      },
      bestOf: 5,
      changes: {
        changeTimestamp: 1692868521,
        changes: ["awayScore.period2"],
      },
      coverage: 92,
      crowdsourcingDataDisplayEnabled: false,
      customId: "zMVcsROVc",
      eventType: "best_of",
      finalResultOnly: false,
      hasGlobalHighlights: true,
      homeScore: {
        current: 1,
        display: 1,
        period1: 8,
        period2: 4,
      },
      homeTeam: {
        country: {
          alpha2: "KR",
          name: "South Korea",
        },
        id: 364374,
        name: "KT Rolster",
        nameCode: "KRO",
        national: false,
        shortName: "KT",
        slug: "kt-rolster",
        sport: {
          id: 72,
          name: "E-sports",
          slug: "esports",
        },
        subTeams: [],
        teamColors: {
          primary: "#52b030",
          secondary: "#52b030",
          text: "#ffffff",
        },
        type: 0,
        userCount: 171,
      },
      id: 11556365,
      slug: "hanwha-life-esports-kt-rolster",
      startTimestamp: 1692864000,
      status: {
        code: 1002,
        description: "Second game",
        type: "inprogress",
      },
      time: {
        currentPeriodStartTimestamp: 1692867316,
      },
      tournament: {
        category: {
          flag: "lol",
          id: 1571,
          name: "LoL",
          slug: "lol",
          sport: {
            id: 72,
            name: "E-sports",
            slug: "esports",
          },
        },
        id: 94794,
        name: "LCK Regional Finals",
        priority: 0,
        slug: "lck-regional-finals",
        uniqueTournament: {
          category: {
            flag: "lol",
            id: 1571,
            name: "LoL",
            slug: "lol",
            sport: {
              id: 72,
              name: "E-sports",
              slug: "esports",
            },
          },
          country: {},
          crowdsourcingEnabled: false,
          displayInverseHomeAwayTeams: false,
          hasEventPlayerStatistics: false,
          hasPerformanceGraphFeature: false,
          id: 16057,
          name: "LCK",
          slug: "lck",
          userCount: 2158,
        },
      },
      winnerCode: 1,
    },
  ],
}

export const esportCat = {
  categories: [
    {
      flag: "lol",
      id: 1571,
      name: "LoL",
      priority: 0,
      slug: "lol",
      sport: {
        id: 72,
        name: "E-sports",
        slug: "esports",
      },
    },
    {
      flag: "dota-2",
      id: 1570,
      name: "Dota 2",
      priority: 0,
      slug: "dota2",
      sport: {
        id: 72,
        name: "E-sports",
        slug: "esports",
      },
    },
    {
      flag: "csgo",
      id: 1572,
      name: "CS:GO",
      priority: 0,
      slug: "csgo",
      sport: {
        id: 72,
        name: "E-sports",
        slug: "esports",
      },
    },
    {
      flag: "other",
      id: 1710,
      name: "Other",
      priority: 0,
      slug: "other",
      sport: {
        id: 72,
        name: "E-sports",
        slug: "esports",
      },
    },
  ],
}
